### ISSUE TITLE
Python libraries?

### ISSUE THREAD

**Issue by ivanistheone** [lyricat/code-knack#1]
This is very interesting. It would be cool to have more broad support for python3 (not possible with skulpt), including libraries. You could then have an entire coding environment in the browser!

Some promising tools in that space are https://pypyjs.org/ and https://github.com/iodide-project/pyodide

**Comment by lyricat** [comment]
Cool. I am seeking for a python 3 support. 

I will compare pypyjs, pyodide and https://www.transcrypt.org/ .

**Comment by lyricat** [comment]
Python 3 and stdlib has been supported in latest code.

Any advice about other libraries support?

**Comment by ivanistheone** [comment]
I don't know how feasible it is, but if you can have pyodide it would be a big win for science:
https://github.com/iodide-project/pyodide#pyodide

demo  https://alpha.iodide.io/notebooks/222/  (select all and press play button in top bar)
via https://hacks.mozilla.org/2019/04/pyodide-bringing-the-scientific-python-stack-to-the-browser/
via https://news.ycombinator.com/item?id=19677721
