### ISSUE TITLE
Html codes with JavaScript

### ISSUE THREAD

**Issue by bsde1234** [lyricat/code-knack#3]
Can I add html with JavaScript

**Comment by lyricat** [comment]
What do you mean by "add html"?

**Comment by bsde1234** [comment]
I mean will this work like jsfiddle?

**Comment by lyricat** [comment]
@bpmottathai not the same. Code-Knack transforms **an existed code block** into a live editor. 
jsfiddle embed a code editor into the webpage.

In Code-Knack way, people write code in an article or webpage; in jsfiddle way, people should write code in jsfiddle and embed a jsfiddle script in the article or webpage.

**Comment by bsde1234** [comment]
That's Ok. But still we can edit codes in code-knack and see the results. But can't save it, I know. But still my question is can we add html support also to codeknack like in jsfiddle?

**Comment by lyricat** [comment]
Oh I get it. Yes of course. Wait a moment.

**Comment by lyricat** [comment]
@bpmottathai done at https://github.com/lyricat/code-knack/commit/fc6a2e84309de10e8c437c0e7ace5e918910ad7b

By the way, I am planing add a canvas or html rendered output. Text-only output is limited.
